### PR TITLE
Rainbow method added, ran tests and added a few tests for Rainbow, ad…

### PR DESCRIPTION
**Pull request by devinRagotzy**
…ded .vs to gitignore

### CODE REVIEW

**Comment by riezebosch** [comment]
Sorry for the late response, just found about your contribution.

**Comment by DevinR528** [comment]
No problem. I hope it's at least sorta helpful it'd be my first accepted pr

**Comment by riezebosch** [comment]
Really like the idea, only a bit struggling with the API. Have a look at https://github.com/riezebosch/crayon/tree/rainbow where I c#'ed your source a little.

**Comment by DevinR528** [comment]
Yea that looks great, much simpler using link. I used it to color console output for a class project, I really like the api.

**Comment by riezebosch** [comment]
Thanks for your contribution and congratulations on your first PR! I changed the Rainbow API afterward and captured it in a separate class. Look at the readme: https://github.com/riezebosch/crayon/tree/master#rainbows-

**Pull request merged**
